cloudhub:
  reconnectionfrequency: "10000"
  reconnectionattempts: "3"
http:
  port: "8091"
basepath: "/api/v1"


AviationInterfaceID: "AviationRyanairInvoice"

anypointmqurl: "https://mq-eu-west-2.anypoint.mulesoft.com/api/v1"