logger:
 category: "/"

payloadlogger:
 dbhost: "192.168.100.37"
 dbport: "1433"
 databasename: "MulesoftIntegration"

db:  
 retryFrequency: "10000" 
 retryAttempts: "3"
 
dbconnectionpool:
 maxsize:  "5"
 minsize:  "0"
  
dbreconnection:
 frequency:  "30000" 
 count:  "3"

isPayloadLoggingEnabled: "true" 

"IsAuthEnabled": "false"

sftp:
 host: "192.168.100.207"
 port: "22"  
 frequency: "100"
 reconnectionfrequency: "10000"
 reconnectionattempts: "3" 
 
smtp:
 host: "192.168.100.191"
 port: "25"

  
            
sftpdir:          
  aviation:
   unprocessed: "/RyanAir/Excel_To_XML/LOCAL"
   processed: "/RyanAir/Excel_To_XML/LOCAL/processed"
   error: "/RyanAir/Excel_To_XML/LOCAL/Error"
   xmlfile: "/RyanAir/Excel_To_XML/LOCAL/RyanairInvoice.xml" 

mailfrom: Aviation@prax.com
mailto: Muthuraj.Pitchaiah@external.prax.com

  
filepattern:
  aviation: "*.xlsx"
                  
frequency:
  aviation: "30"
 
 
cloudhub:
 env: "4a73d452-9b71-44fc-87b4-10b579c5abef"   
    
