alertlogin:
 password: "![Uni4Nl7Gfmnbw5PHcRIMpQ==]"
 username: "![JNlySJlOy3DuqDO4k15L92zxVrsH5MXp]"
 
payloadlogger:
 dbuser: "![6OL2/rNYbe+LwVctgEj0xw==]"
 dbpassword: "![ILbbjBCvKSzTblprFBrvUVFe1ls/JPu+5rmAVzwigo4=]"
 
 
sftp:
 username: "![qKCGULrAU8UxwMumvjiAoQ==]"
 password: "![CicAuopeKZC+TijcGXKnaaiQwge8EdKw]"  
 
anypointmq:
 clientid: "![qvNkoNpWSseFDWu7akRvZhhl5KQcEsdeRiL4QE73y7Nv0rNyF8ua+Q==]"
 clientsecret: "![fouCWZeNvQ/LC7Eb9/Xl/4TOEoexKSnUdQCCFeKO8w84Qox2u8mQFA==]" 

 
