alertlogin:
 password: "![Uni4Nl7Gfmnbw5PHcRIMpQ==]"
 username: "![JNlySJlOy3DuqDO4k15L92zxVrsH5MXp]"
 
payloadlogger:
 dbuser: "![6OL2/rNYbe+LwVctgEj0xw==]"
 dbpassword: "![ILbbjBCvKSzTblprFBrvUVFe1ls/JPu+5rmAVzwigo4=]"
 

sftp:
 username: "![qKCGULrAU8UxwMumvjiAoQ==]"
 password: "![CicAuopeKZC+TijcGXKnaaiQwge8EdKw]"
 
anypointmq:
 clientid: "![4Z9j/lJBLwn3fzGXx5QR/hfQew40JFMD6l7euSi+09WKaxf5tdyqqQ==]"
 clientsecret: "![yY1/rJEVS/gyaeleINtNV4Xba4sJgg5+oBGy3vt8q4Ka7NDb3AvR2g==]"