logger:
 category: "/"

payloadlogger:
 dbhost: "192.168.100.233"
 dbport: "1433"
 databasename: "MulesoftIntegration"
 
db:  
 retryFrequency: "10000" 
 retryAttempts: "3"
 
dbconnectionpool:
 maxsize:  "5"
 minsize:  "0"
  
dbreconnection:
 frequency:  "30000" 
 count:  "3"

isPayloadLoggingEnabled: "true" 

"IsAuthEnabled": "false"

sftp:
 host: "192.168.100.207"
 port: "22"  
 frequency: "100"
 reconnectionfrequency: "10000"
 reconnectionattempts: "3"

smtp:
 host: "192.168.100.191"
 port: "25"

sftpdir:          
  aviation:
   unprocessed: "/RyanAir/Excel_To_XML/PROD"
   processed: "/RyanAir/Excel_To_XML/PROD/processed"
   error: "/RyanAir/Excel_To_XML/PROD/Error"
   xmlfile: "/RyanAir/Excel_To_XML/PROD/RyanairInvoice.xml" 

mailfrom: Aviation@prax.com
mailto: Muthuraj.Pitchaiah@external.prax.com,Samir.Pipalia@external.prax.com,Ian.Stanley@Harvestenergy.com

  
filepattern:
  aviation: "*.xlsx"
                  
frequency:
  aviation: "30"
 
cloudhub:
 env: "afd3e6db-869f-4d89-89c1-99042dcef9bc"