logger:
 category: "/"

payloadlogger:
 dbhost: "192.168.100.37"
 dbport: "1433"
 databasename: "MulesoftIntegration_Stage"

db:  
 retryFrequency: "10000" 
 retryAttempts: "3"
 
dbconnectionpool:
 maxsize:  "5"
 minsize:  "0"
  
dbreconnection:
 frequency:  "30000" 
 count:  "3"

isPayloadLoggingEnabled: "true" 

"IsAuthEnabled": "false"

sftp:
 host: "192.168.100.207"
 port: "22"  
 frequency: "100"
 reconnectionfrequency: "10000"
 reconnectionattempts: "3"       

smtp:
 host: "192.168.100.191"
 port: "25"
  
sftpdir:          
  aviation:
   unprocessed: "/RyanAir/Excel_To_XML/DEV"
   processed: "/RyanAir/Excel_To_XML/DEV/processed"
   error: "/RyanAir/Excel_To_XML/DEV/Error"
   xmlfile: "/RyanAir/Excel_To_XML/DEV/RyanairInvoice.xml"
   
mailfrom: Aviation@prax.com
mailto: Muthuraj.Pitchaiah@external.prax.com,Samir.Pipalia@external.prax.com

  
filepattern:
  aviation: "*.xlsx"
   
frequency:
  aviation: "30"
                  
         
  
cloudhub:
 env: "d57b89bf-834f-4759-9d84-2578d71654f3"