alertlogin:
 password: "![Uni4Nl7Gfmnbw5PHcRIMpQ==]"
 username: "![JNlySJlOy3DuqDO4k15L92zxVrsH5MXp]"
 
payloadlogger:
 dbuser: "![6OL2/rNYbe8kMZGAHtjTkKyGSQFoGHfb]"
 dbpassword: "![I4n0m/uJLhJDo8TQMJXCRFaLAKBSyd56UXuNahgnCKQ=]"
 
sftp:
 username: "![qKCGULrAU8UxwMumvjiAoQ==]"
 password: "![CicAuopeKZC+TijcGXKnaaiQwge8EdKw]"

anypointmq:
 clientid: "![BcuVEp27oGveZ3D1m60HN6JRY2WBWMv+QshxtYoMmCRA/YCcLulAKg==]"
 clientsecret: "![NwugsVuMNYfec0RE+BuPTSDnn4Eb85pgqk9wIzyHtwgBv10qqvZCWQ==]"   